version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: 'login'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'db-name'
    ports:
      - '15432:5432'

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - '16379:6379'


