name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    # Checkout репозитория
    - name: Checkout repository
      uses: actions/checkout@v3

    # Установка Go
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23

    # Кэширование зависимостей
    - name: Cache Go Modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    # Установка зависимостей
    - name: Install dependencies
      run: go mod tidy

    # Запуск линтинга
    - name: Run linter
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.53.3
        golangci-lint run

    # Запуск тестов
    - name: Run tests
      run: go test -v ./...

    # Проверка сборки
    - name: Build the application
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o my-app ./cmd/app
